on:
  - push
  - pull_request


jobs:
  code-quality:
    name: Run Code Quality tools
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: python -m pip install poetry
      - run: poetry install
      - run: poetry run black . --check
      - run: poetry run mypy .
      - run: poetry run flake8 .
      - run: poetry run pytest .

